import {
  Accessibility,
  AirVent,
  Armchair,
  Award,
  Baby,
  BadgeDollarSign,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  BedDouble,
  BedSingle,
  Bike,
  BrickWall,
  Building,
  Building2,
  BusFront,
  Calculator,
  CalendarClock,
  Camera,
  Car,
  CarFront,
  CarTaxiFront,
  Cctv,
  ChefHat,
  CheckCircle2,
  Church,
  Clapperboard,
  ClipboardCheck,
  Coffee,
  Compass,
  Construction,
  CookingPot,
  CreditCard,
  Crown,
  DoorClosed,
  DoorOpen,
  Droplets,
  Dumbbell,
  Expand,
  Factory,
  Fan,
  Fence,
  FileText,
  Flame,
  Flower,
  Gamepad2,
  Goal,
  GraduationCap,
  Hammer,
  Handshake,
  HardHat,
  Heart,
  Home,
  Hospital,
  Hotel,
  HousePlug,
  HousePlus,
  KeyRound,
  LampCeiling,
  LampFloor,
  Landmark,
  Leaf,
  Lock,
  MapPin,
  MapPinHouse,
  MapPinned,
  Medal,
  Mic,
  MonitorPlay,
  Mountain,
  Music,
  Navigation,
  NotebookText,
  PaintBucket,
  Palette,
  PanelTopOpen,
  PartyPopper,
  Percent,
  PiggyBank,
  Plane,
  PlugZap,
  Popcorn,
  Projector,
  Puzzle,
  QrCode,
  ReceiptText,
  Refrigerator,
  Route,
  Ruler,
  School,
  ScrollText,
  ShieldCheck,
  ShieldUser,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Sofa,
  SolarPanel,
  Sparkles,
  Sprout,
  SquareParking,
  Star,
  Stethoscope,
  Store,
  Sun,
  TentTree,
  Theater,
  ThermometerSun,
  TicketCheck,
  Toilet,
  TrainFront,
  TreePalm,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UsersRound,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  WashingMachine,
  Waves,
  WavesLadder,
  Wifi,
  Wind,
  Wine,
  Zap
} from "lucide-react";

export const PROPERTY_FEATURE_ICONS = {
  accessibility: Accessibility,
  air: AirVent,
  armchair: Armchair,
  award: Award,
  baby: Baby,
  banknote: Banknote,
  barbecue: Flame,
  basket: ShoppingBasket,
  bath: Bath,
  battery: BatteryCharging,
  bed: BedDouble,
  "bed-single": BedSingle,
  bike: Bike,
  "brick-wall": BrickWall,
  building: Building2,
  "building-tower": Building,
  bus: BusFront,
  calculator: Calculator,
  calendar: CalendarClock,
  camera: Camera,
  car: Car,
  "car-front": CarFront,
  cctv: Cctv,
  check: CheckCircle2,
  chef: ChefHat,
  church: Church,
  cinema: Clapperboard,
  clipboard: ClipboardCheck,
  coffee: Coffee,
  compass: Compass,
  construction: Construction,
  "credit-card": CreditCard,
  crown: Crown,
  document: FileText,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  dumbbell: Dumbbell,
  elevator: PanelTopOpen,
  energy: Zap,
  expand: Expand,
  factory: Factory,
  fan: Fan,
  fence: Fence,
  flower: Flower,
  gamepad: Gamepad2,
  hammer: Hammer,
  handshake: Handshake,
  "hard-hat": HardHat,
  health: Stethoscope,
  heart: Heart,
  home: Home,
  hospital: Hospital,
  hotel: Hotel,
  "house-plug": HousePlug,
  "house-plus": HousePlus,
  key: KeyRound,
  kitchen: CookingPot,
  "lamp-ceiling": LampCeiling,
  "lamp-floor": LampFloor,
  leaf: Leaf,
  lock: Lock,
  map: MapPin,
  "map-house": MapPinHouse,
  "map-pin": MapPinned,
  market: ShoppingCart,
  medal: Medal,
  mic: Mic,
  money: BadgeDollarSign,
  mountain: Mountain,
  music: Music,
  navigation: Navigation,
  notebook: NotebookText,
  paint: PaintBucket,
  palette: Palette,
  parking: SquareParking,
  party: PartyPopper,
  percent: Percent,
  "badge-percent": BadgePercent,
  "piggy-bank": PiggyBank,
  plane: Plane,
  playground: Puzzle,
  pool: WavesLadder,
  popcorn: Popcorn,
  projector: Projector,
  "qr-code": QrCode,
  receipt: ReceiptText,
  refrigerator: Refrigerator,
  route: Route,
  ruler: Ruler,
  sauna: ThermometerSun,
  school: School,
  scroll: ScrollText,
  shield: ShieldCheck,
  "shield-user": ShieldUser,
  shower: ShowerHead,
  "shopping-bag": ShoppingBag,
  sofa: Sofa,
  soccer: Goal,
  solar: SolarPanel,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  store: Store,
  sun: Sun,
  taxi: CarTaxiFront,
  tennis: Trophy,
  theater: Theater,
  ticket: TicketCheck,
  "tent-tree": TentTree,
  toilet: Toilet,
  train: TrainFront,
  "tree-palm": TreePalm,
  "tree-pine": TreePine,
  trees: Trees,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  umbrella: Umbrella,
  users: UsersRound,
  utensils: UtensilsCrossed,
  volleyball: Volleyball,
  wallet: Wallet,
  water: Droplets,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
  wine: Wine
};

export function getPropertyFeatureIcon(icon) {
  return PROPERTY_FEATURE_ICONS[icon] || PROPERTY_FEATURE_ICONS.sparkles;
}

export default function PropertyFeatureIcon({ icon, className = "h-4 w-4 shrink-0 text-brand", ...props }) {
  const Icon = getPropertyFeatureIcon(icon);
  return <Icon className={className} aria-hidden="true" {...props} />;
}
